---
- name: Create web directory if it does not exist
  file:
    path: "/home/{{ PI_USERNAME }}/web"
    state: directory
- name: Push front sources
  synchronize:
    src: "{{ PROJECT_PATH }}/software/modules/gui/web/build"
    dest: "/home/{{ PI_USERNAME }}/web"
