---
- hosts: localhost
  gather_facts: no
  roles:
    - include_role:
      name: build_back
    - include_role:
      name: build_front
- hosts: pi
  gather_facts: no
  roles:
    - include_role:
      name: push_back
      become: true
    - include_role:
      name: push_front
      become: true
    - include_role:
      name: push_missions
      become: true
    - include_role:
      name: run
      become: true
